auto: true
markdown: rdiscount
pygments: true

title: Sam's Website

url: http://samcennis.github.com

permalink: /:year/:month/:day/:title/

author:
    name: Sam Ennis
    email: sam.c.ennis@gmail.com
    github: samcennis
    youtube: pelicanbeam
    gravatar: /img/blogHeader-small.jpg